<?xml version="1.0" encoding="utf-8"?><Database Name="Bco_WebserviceWithRest" Class="webservicewithrestDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=s744;Initial Catalog=Bco_WebserviceWithRest;Persist Security Info=True;User ID=sa" SettingsObjectName="TrabalhoRestBLL.Properties.Settings" SettingsPropertyName="Bco_WebserviceWithRestConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ListaTarefa" Member="ListaTarefas">
    <Type Name="ListaTarefa">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Cor" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UsuarioId" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="ListaTarefa_Tarefa" Member="Tarefas" ThisKey="Id" OtherKey="ListaTarefaId" Type="Tarefa" />
      <Association Name="Usuario_ListaTarefa" Member="Usuario" ThisKey="UsuarioId" OtherKey="Id" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Usuario" Member="Usuarios">
    <Type Name="Usuario">
      <Column Name="Id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Senha" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Facebook" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Usuario_ListaTarefa" Member="ListaTarefas" ThisKey="Id" OtherKey="UsuarioId" Type="ListaTarefa" />
    </Type>
  </Table>
  <Table Name="dbo.Tarefa" Member="Tarefas">
    <Type Name="Tarefa">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Descricao" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ListaTarefaId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ListaTarefa_Tarefa" Member="ListaTarefa" ThisKey="ListaTarefaId" OtherKey="Id" Type="ListaTarefa" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
</Database>