//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace RepositoryAPW.wswithrest {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="webservicewithrestSoap", Namespace="roberto-oliveira")]
    public partial class webservicewithrest : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback check_userOperationCompleted;
        
        private System.Threading.SendOrPostCallback return_user_by_idOperationCompleted;
        
        private System.Threading.SendOrPostCallback return_user_by_emailOperationCompleted;
        
        private System.Threading.SendOrPostCallback return_list_usersOperationCompleted;
        
        private System.Threading.SendOrPostCallback create_userOperationCompleted;
        
        private System.Threading.SendOrPostCallback update_userOperationCompleted;
        
        private System.Threading.SendOrPostCallback delete_userOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public webservicewithrest() {
            this.Url = global::RepositoryAPW.Properties.Settings.Default.RepositoryAPW_wswithrest_webservicewithrest;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event check_userCompletedEventHandler check_userCompleted;
        
        /// <remarks/>
        public event return_user_by_idCompletedEventHandler return_user_by_idCompleted;
        
        /// <remarks/>
        public event return_user_by_emailCompletedEventHandler return_user_by_emailCompleted;
        
        /// <remarks/>
        public event return_list_usersCompletedEventHandler return_list_usersCompleted;
        
        /// <remarks/>
        public event create_userCompletedEventHandler create_userCompleted;
        
        /// <remarks/>
        public event update_userCompletedEventHandler update_userCompleted;
        
        /// <remarks/>
        public event delete_userCompletedEventHandler delete_userCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("roberto-oliveira/check_user", RequestNamespace="roberto-oliveira", ResponseNamespace="roberto-oliveira", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool check_user(string email) {
            object[] results = this.Invoke("check_user", new object[] {
                        email});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void check_userAsync(string email) {
            this.check_userAsync(email, null);
        }
        
        /// <remarks/>
        public void check_userAsync(string email, object userState) {
            if ((this.check_userOperationCompleted == null)) {
                this.check_userOperationCompleted = new System.Threading.SendOrPostCallback(this.Oncheck_userOperationCompleted);
            }
            this.InvokeAsync("check_user", new object[] {
                        email}, this.check_userOperationCompleted, userState);
        }
        
        private void Oncheck_userOperationCompleted(object arg) {
            if ((this.check_userCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.check_userCompleted(this, new check_userCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("roberto-oliveira/return_user_by_id", RequestNamespace="roberto-oliveira", ResponseNamespace="roberto-oliveira", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string return_user_by_id(string id) {
            object[] results = this.Invoke("return_user_by_id", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void return_user_by_idAsync(string id) {
            this.return_user_by_idAsync(id, null);
        }
        
        /// <remarks/>
        public void return_user_by_idAsync(string id, object userState) {
            if ((this.return_user_by_idOperationCompleted == null)) {
                this.return_user_by_idOperationCompleted = new System.Threading.SendOrPostCallback(this.Onreturn_user_by_idOperationCompleted);
            }
            this.InvokeAsync("return_user_by_id", new object[] {
                        id}, this.return_user_by_idOperationCompleted, userState);
        }
        
        private void Onreturn_user_by_idOperationCompleted(object arg) {
            if ((this.return_user_by_idCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.return_user_by_idCompleted(this, new return_user_by_idCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("roberto-oliveira/return_user_by_email", RequestNamespace="roberto-oliveira", ResponseNamespace="roberto-oliveira", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string return_user_by_email(string email) {
            object[] results = this.Invoke("return_user_by_email", new object[] {
                        email});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void return_user_by_emailAsync(string email) {
            this.return_user_by_emailAsync(email, null);
        }
        
        /// <remarks/>
        public void return_user_by_emailAsync(string email, object userState) {
            if ((this.return_user_by_emailOperationCompleted == null)) {
                this.return_user_by_emailOperationCompleted = new System.Threading.SendOrPostCallback(this.Onreturn_user_by_emailOperationCompleted);
            }
            this.InvokeAsync("return_user_by_email", new object[] {
                        email}, this.return_user_by_emailOperationCompleted, userState);
        }
        
        private void Onreturn_user_by_emailOperationCompleted(object arg) {
            if ((this.return_user_by_emailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.return_user_by_emailCompleted(this, new return_user_by_emailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("roberto-oliveira/return_list_users", RequestNamespace="roberto-oliveira", ResponseNamespace="roberto-oliveira", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string return_list_users() {
            object[] results = this.Invoke("return_list_users", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void return_list_usersAsync() {
            this.return_list_usersAsync(null);
        }
        
        /// <remarks/>
        public void return_list_usersAsync(object userState) {
            if ((this.return_list_usersOperationCompleted == null)) {
                this.return_list_usersOperationCompleted = new System.Threading.SendOrPostCallback(this.Onreturn_list_usersOperationCompleted);
            }
            this.InvokeAsync("return_list_users", new object[0], this.return_list_usersOperationCompleted, userState);
        }
        
        private void Onreturn_list_usersOperationCompleted(object arg) {
            if ((this.return_list_usersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.return_list_usersCompleted(this, new return_list_usersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("roberto-oliveira/create_user", RequestNamespace="roberto-oliveira", ResponseNamespace="roberto-oliveira", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string create_user(string nome, string email, string senha) {
            object[] results = this.Invoke("create_user", new object[] {
                        nome,
                        email,
                        senha});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void create_userAsync(string nome, string email, string senha) {
            this.create_userAsync(nome, email, senha, null);
        }
        
        /// <remarks/>
        public void create_userAsync(string nome, string email, string senha, object userState) {
            if ((this.create_userOperationCompleted == null)) {
                this.create_userOperationCompleted = new System.Threading.SendOrPostCallback(this.Oncreate_userOperationCompleted);
            }
            this.InvokeAsync("create_user", new object[] {
                        nome,
                        email,
                        senha}, this.create_userOperationCompleted, userState);
        }
        
        private void Oncreate_userOperationCompleted(object arg) {
            if ((this.create_userCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.create_userCompleted(this, new create_userCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("roberto-oliveira/update_user", RequestNamespace="roberto-oliveira", ResponseNamespace="roberto-oliveira", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string update_user(int id, string nome, string email, string senha) {
            object[] results = this.Invoke("update_user", new object[] {
                        id,
                        nome,
                        email,
                        senha});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void update_userAsync(int id, string nome, string email, string senha) {
            this.update_userAsync(id, nome, email, senha, null);
        }
        
        /// <remarks/>
        public void update_userAsync(int id, string nome, string email, string senha, object userState) {
            if ((this.update_userOperationCompleted == null)) {
                this.update_userOperationCompleted = new System.Threading.SendOrPostCallback(this.Onupdate_userOperationCompleted);
            }
            this.InvokeAsync("update_user", new object[] {
                        id,
                        nome,
                        email,
                        senha}, this.update_userOperationCompleted, userState);
        }
        
        private void Onupdate_userOperationCompleted(object arg) {
            if ((this.update_userCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.update_userCompleted(this, new update_userCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("roberto-oliveira/delete_user", RequestNamespace="roberto-oliveira", ResponseNamespace="roberto-oliveira", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string delete_user(int Id) {
            object[] results = this.Invoke("delete_user", new object[] {
                        Id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void delete_userAsync(int Id) {
            this.delete_userAsync(Id, null);
        }
        
        /// <remarks/>
        public void delete_userAsync(int Id, object userState) {
            if ((this.delete_userOperationCompleted == null)) {
                this.delete_userOperationCompleted = new System.Threading.SendOrPostCallback(this.Ondelete_userOperationCompleted);
            }
            this.InvokeAsync("delete_user", new object[] {
                        Id}, this.delete_userOperationCompleted, userState);
        }
        
        private void Ondelete_userOperationCompleted(object arg) {
            if ((this.delete_userCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.delete_userCompleted(this, new delete_userCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void check_userCompletedEventHandler(object sender, check_userCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class check_userCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal check_userCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void return_user_by_idCompletedEventHandler(object sender, return_user_by_idCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class return_user_by_idCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal return_user_by_idCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void return_user_by_emailCompletedEventHandler(object sender, return_user_by_emailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class return_user_by_emailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal return_user_by_emailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void return_list_usersCompletedEventHandler(object sender, return_list_usersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class return_list_usersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal return_list_usersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void create_userCompletedEventHandler(object sender, create_userCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class create_userCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal create_userCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void update_userCompletedEventHandler(object sender, update_userCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class update_userCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal update_userCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void delete_userCompletedEventHandler(object sender, delete_userCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class delete_userCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal delete_userCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591